title: Himani Jaiswal | Data Analyst | Business Intelligence Expert
description: >
  Highly motivated and detail-oriented Data Analyst with over 3 years of experience in leveraging advanced data analytics and business intelligence tools. 
  Proficient in SQL, Python, Power BI, Tableau, and data warehousing technologies like Snowflake and Azure Synapse. Passionate about transforming complex data into actionable insights that drive strategic decision-making, process optimization, and business growth.
  With a solid background in the banking, retail, and insurance industries, I’ve contributed to major projects at Loblaws and Sunlife Insurance, improving data integrity, creating innovative dashboards, and optimizing data-driven strategies. 
  Committed to continuous learning and delivering data solutions that help organizations enhance performance and meet their business objectives.

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # Your Google Analytics tracking ID here
